// src/components/sections/Contact.vue
<template>
  <section
    id="contact-section"
    class="relative min-h-svh w-full overflow-y-clip p-[4vh] select-none"
  >
    <div
      class="flex-center relative h-[92vh] w-full flex-col rounded-lg bg-flax-smoke-50 uppercase"
    >
      <video
        class="absolute bottom-0 left-0 size-full rounded-lg object-cover object-bottom brightness-50"
        :src="contact"
        autoplay
        muted
        loop
        playsinline
      ></video>
      <!-- :style="'background-image: url(' + contact + ') !important; '" -->
      <div class="flex-center z-10 flex-col gap-y-10">
        <p
          class="heading-4 text-flax-smoke-800 max-w-[30ch] text-center font-mono"
        >
          Complex challenges require intelligent, scalable architectures.
        </p>
        <h3
          id="make-it-happen"
          class="heading-1 text-flax-smoke-800 max-w-[10ch] text-center leading-none"
          v-html="makeItHappen"
        ></h3>
        <div
          class="mt-[5%] flex scale-150 items-center lg:scale-[1.5] xl:scale-[3] 2xl:scale-[3.5]"
        >
          <!-- <Button
            :data-cal-namespace="dataCalNamespace"
            :data-cal-link="dataCalLink"
            :data-cal-config="dataCalConfig"
            label="Get in touch"
          /> -->
          <Button label="Get in touch" url="https://wa.me/919121661507" />
        </div>
      </div>
      <div
        class="absolute bottom-5 flex w-full items-center justify-center px-5 md:justify-between"
      >
        <div class="hidden md:flex">
          <div class="border-flax-smoke-300 relative border">
            <Vue3Lottie
              ref="customControl"
              :animationData="earthLottie"
              :loop="true"
              :autoPlay="true"
            />
          </div>
          <div
            class="flex-center py border-flax-smoke-300 text-flax-smoke-300 w-fit flex-col border border-l-0 font-mono"
          >
            <p
              class="border-flax-smoke-300 flex size-full items-center justify-start border-b pr-2 pl-1 font-bold"
            >
              Engineering Globally
            </p>
            <p class="flex size-full items-center justify-start pr-2 pl-1">
              {{ AvailableForWorkDate }}
            </p>
          </div>
        </div>

        <div class="heading-6 text-flax-smoke-500 w-fit">
          <p class="w-full font-bold uppercase">For further inquiries</p>
          <Link
            class="text-flax-smoke-300 h-6 text-right font-medium tracking-wider lowercase"
            label="lokeshramchand@gmail.com"
            :icon="true"
            url="mailto:lokeshramchand@gmail.com"
          />
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
  import { earthLottie } from '@/assets/videos';
  import { Button } from '../common';
  import { Vue3Lottie } from 'vue3-lottie';
  import Link from '../Link.vue';
  import { contact } from '@/assets/videos';
  import { onBeforeMount, onMounted, ref } from 'vue';
  import { getAvailableForWorkDate, textSplitterIntoChar } from '@/functions';
  import { animateSplitText } from '@/animations';
  // import { dataCalConfig, dataCalLink, dataCalNamespace } from '@/data';

  const makeItHappen = ref("Let's engineer it");
  const AvailableForWorkDate = ref('');

  onBeforeMount(() => {
    makeItHappen.value = textSplitterIntoChar(makeItHappen.value);
    AvailableForWorkDate.value = getAvailableForWorkDate();
  });

  onMounted(() => {
    animateSplitText(
      '#make-it-happen .letters',
      '#make-it-happen',
      1.5,
      0.01,
      0,
    );
  });
</script>

<style>
  .lottie-animation-container {
    height: 100% !important;
  }
  .lottie-animation-container svg {
    height: 100px !important;
    width: fit-content !important;
    margin: -10px -30px !important;
    padding: 0 !important;
  }

  .lottie-animation-container {
    --lottie-animation-container-width: fit-content !important;
    --lottie-animation-container-height: 0% !important;
  }
</style>

// src/components/sections/Contact.tsx
"use client";

import { useEffect, useRef } from "react";
import { gsap, prefersReducedMotion } from "@/lib/gsap";
import { siteConfig } from "@/lib/data";

export default function Contact() {
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const section = sectionRef.current;
    if (!section || prefersReducedMotion()) return;

    const el = section.querySelector("[data-reveal]");
    if (!el) return;
    gsap.set(el, { autoAlpha: 0, y: 28 });
    gsap.to(el, {
      autoAlpha: 1,
      y: 0,
      duration: 1,
      ease: "power3.out",
      scrollTrigger: {
        trigger: section,
        start: "top 80%",
        toggleActions: "play none none none",
      },
    });
  }, []);

  return (
    <section
      id="contact"
      ref={sectionRef}
      className="relative flex min-h-screen items-center overflow-hidden border-t border-paper-500/10"
    >
      <video
        className="absolute inset-0 h-full w-full object-cover opacity-25"
        src="/videos/contact.mp4"
        poster="/images/contact-poster.webp"
        autoPlay
        muted
        loop
        playsInline
        preload="none"
        aria-hidden="true"
      />
      <div className="absolute inset-0 bg-gradient-to-b from-void-950 via-void-950/60 to-void-950" />

      <div data-reveal className="padding-x relative w-full py-32 text-center">
        <p className="font-mono text-sm text-amber-400">
          Complex challenges require intelligent, scalable architectures.
        </p>
        <h2 className="font-title heading-display mx-auto mt-6 max-w-4xl text-paper-500">
          Let&rsquo;s build the next one together.
        </h2>
        <div className="mt-10 flex flex-wrap items-center justify-center gap-6">
          <a
            href={siteConfig.whatsapp}
            target="_blank"
            rel="noreferrer noopener"
            data-cursor="hover"
            className="rounded-full bg-amber-500 px-8 py-4 text-sm font-medium text-void-950 transition-transform hover:scale-105"
          >
            Get in touch
          </a>
          <a
            href={`mailto:${siteConfig.email}`}
            data-cursor="hover"
            className="text-sm text-paper-300 underline decoration-paper-500/30 underline-offset-4 hover:text-amber-400"
          >
            {siteConfig.email}
          </a>
        </div>
        <p className="mt-16 font-mono text-xs text-paper-100">
          {siteConfig.locationCountry} — Engineering globally
        </p>
      </div>
    </section>
  );
}
