// src/components/common/Nav.tsx
'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { navLinks, socialLinks } from '@/lib/data';
import { cn } from '@/lib/utils';
import { gsap, prefersReducedMotion } from '@/lib/gsap';

function BurgerButton({ open, onClick }: { open: boolean; onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-expanded={open}
      aria-controls="mobile-menu"
      aria-label={open ? 'Close menu' : 'Open menu'}
      className="relative z-70 flex h-10 w-10 flex-col items-center justify-center gap-[5px] md:hidden"
    >
      <span
        className={cn(
          'block h-px w-6 bg-paper-500 transition-transform duration-300',
          open && 'translate-y-[6.5px] rotate-45',
        )}
      />
      <span
        className={cn(
          'block h-px w-6 bg-paper-500 transition-transform duration-300',
          open && '-translate-y-[6.5px] -rotate-45',
        )}
      />
    </button>
  );
}

function MobileMenu({ open, onClose }: { open: boolean; onClose: () => void }) {
  const panelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const panel = panelRef.current;
    if (!panel) return;

    if (open) {
      document.documentElement.classList.add('overflow-hidden');
      window.__lenis?.stop();
      if (!prefersReducedMotion()) {
        const items = panel.querySelectorAll('[data-menu-item]');
        gsap.set(items, { autoAlpha: 0, y: 16 });
        gsap.to(items, { autoAlpha: 1, y: 0, duration: 0.5, stagger: 0.06, ease: 'power3.out' });
      }
    } else {
      document.documentElement.classList.remove('overflow-hidden');
      window.__lenis?.start();
    }
  }, [open]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  return (
    <div
      id="mobile-menu"
      ref={panelRef}
      role="dialog"
      aria-modal="true"
      className={cn(
        'fixed inset-0 z-60 flex flex-col justify-between bg-void-950 px-6 pt-28 pb-12 transition-opacity duration-300 md:hidden',
        open ? 'pointer-events-auto opacity-100' : 'pointer-events-none opacity-0',
      )}
    >
      <nav aria-label="Mobile">
        <ul className="space-y-2">
          {navLinks.map((link) => (
            <li key={link.label} data-menu-item>
              <Link
                href={link.url}
                onClick={onClose}
                className="font-title heading-3 block text-paper-500 transition-colors hover:text-amber-400"
              >
                {link.label}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
      <div data-menu-item className="flex gap-6 border-t border-paper-500/10 pt-6">
        {socialLinks.map((link) => (
          <a
            key={link.label}
            href={link.url}
            target="_blank"
            rel="noreferrer noopener"
            className="text-sm text-paper-300 hover:text-amber-400"
          >
            {link.label}
          </a>
        ))}
      </div>
    </div>
  );
}

export default function Nav() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40);
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  return (
    <header
      className={cn(
        'fixed inset-x-0 top-0 z-70 transition-colors duration-500',
        (scrolled || open) && 'bg-void-950/80 backdrop-blur-md',
      )}
    >
      <div className="padding-x flex items-center justify-between py-5">
        <Link
          href="/#top"
          onClick={() => setOpen(false)}
          className="font-title text-sm tracking-[0.2em] text-paper-500 uppercase"
        >
          Lokesh Ram Chand
        </Link>
        <nav className="hidden items-center gap-8 md:flex" aria-label="Primary">
          {navLinks.map((link) => (
            <Link
              key={link.label}
              href={link.url}
              className="text-sm text-paper-200 transition-colors hover:text-amber-400"
              data-cursor="hover"
            >
              {link.label}
            </Link>
          ))}
        </nav>
        <a
          href="#contact"
          className="hidden rounded-full border border-paper-500/20 px-4 py-2 text-xs tracking-wide text-paper-300 transition-colors hover:border-amber-400 hover:text-amber-400 md:inline-block"
          data-cursor="hover"
        >
          Available for work
        </a>
        <BurgerButton open={open} onClick={() => setOpen((v) => !v)} />
      </div>

      <MobileMenu open={open} onClose={() => setOpen(false)} />
    </header>
  );
}

// src/components/common/Nav.vue
<template>
  <BurgerMenuBtn
    @click="toggleBtnClickAnimation"
    class="z-9999 scale-0 drop-shadow-lg max-md:scale-100"
    id="burger"
  />

  <div
    @click="toggleBtnClickAnimation"
    class="bg-flax-smoke-50 fixed inset-0 z-9998 size-full opacity-50 select-none"
    :class="{ hidden: !isNavbarOpen }"
  ></div>

  <div
    tabindex="0"
    id="navbar"
    @keydown.esc="toggleBtnClickAnimation()"
    class="bg-flax-smoke-950 fixed top-[1dvh] right-0 z-9998 h-[98dvh] w-full translate-x-full rounded-s-lg p-5 will-change-auto select-none focus:outline-hidden max-md:w-[98%] sm:p-10 md:w-3/5 md:px-20 lg:w-2/5"
  >
    <Circles id="circles" class="absolute top-0 right-0 opacity-25" />
    <div class="flex h-full flex-col items-center justify-between">
      <div class="relative z-19 w-full">
        <ul
          class="heading-2 text-flax-smoke-50 mt-12 font-bold md:mt-24"
          id="navLinks"
        >
          <li
            class="overflow-y-clip"
            v-for="l in navbarLinks"
            :key="l.label"
            :id="l.label"
          >
            <a
              :href="l.url"
              @click="(e) => handleSectionClick(e, l.url)"
              class="group my-2 flex h-full w-fit translate-y-full cursor-pointer items-center justify-start leading-none will-change-auto"
            >
              <span
                class="bg-flax-smoke-50 h-4 w-4 scale-0 rounded-full opacity-0 transition-all duration-300 ease-in-out group-hover:scale-100 group-hover:opacity-100"
              ></span>
              <p
                class="font-fancy -translate-x-5 transition-all duration-300 ease-in-out group-hover:translate-x-5"
              >
                {{ l.label }}
              </p>
            </a>
          </li>
        </ul>
      </div>

      <div class="w-full">
        <div class="text-flax-smoke-50 mt-2 h-full font-normal">
          <p class="text-left text-sm font-bold uppercase">Email address</p>
          <Link
            class="font-medium tracking-wider"
            tag="p"
            label="lokeshramchand@gmail.com"
            url="mailto:lokeshramchand@gmail.com"
          />
          <div class="mt-6 flex flex-wrap justify-start gap-1">
            <Button
              class="contact border-flax-smoke-600 border opacity-0"
              v-for="social in socialLinks"
              :key="social.label"
              :label="social.label"
              :url="social.url"
            />
          </div>
        </div>
      </div>
    </div>
  </div>

  <header
    :class="$attrs.class"
    class="padding-x absolute inset-0 z-20 h-fit -translate-y-full pt-6 will-change-auto"
  >
    <nav class="flex justify-between">
      <MagneticEffect
        :magnetoStrengthVal="20"
        :magnetoTextStrengthVal="10"
        divId="name-container"
        textId="name"
      >
        <div id="name-container" class="group -m-10 h-fit cursor-pointer p-10">
          <h2
            id="name"
            class="font-fancy flex items-start text-xl font-extrabold uppercase md:text-3xl"
          >
            Lokesh
            <span
              class="font-fancy inline! origin-center! text-xl transition-transform duration-500 ease-in-out group-hover:rotate-[360deg]"
              >&copy;</span
            >
          </h2>
        </div>
      </MagneticEffect>

      <div class="flex justify-start">
        <p
          class="heading-6 font-fancy text-flax-smoke-400 hidden font-bold uppercase select-none md:block"
        >
          available for freelancers <br />
          work and collaboration
        </p>
      </div>
      <div class="flex">
        <ul
          class="hidden w-full flex-1 gap-1 overflow-y-hidden text-lg font-medium md:flex md:gap-2 md:text-xl lg:gap-4 lg:text-2xl xl:text-3xl"
        >
          <Link
            v-for="(l, index) in navLinks"
            :key="l.label"
            tag="li"
            :label="l.label + (index !== navLinks.length - 1 ? ',' : '')"
            :url="l.url"
          />
        </ul>
      </div>
    </nav>
  </header>
</template>
<script setup lang="ts">
  import { ref, watch } from 'vue';

  import { Link, BurgerMenuBtn, MagneticEffect } from '..';
  import { Circles } from '../design';
  import { Button } from '../common';

  import { animateNavbarEnter, animateNavbarLeave } from '@/animations';
  import { navbarLinks, navLinks, socialLinks } from '@/data';
  import { useSectionNav } from '@/functions';

  const isNavbarOpen = ref(false);
  const { goToSection } = useSectionNav();

  const toggleBtnClickAnimation = () => {
    isNavbarOpen.value = !isNavbarOpen.value;

    // animate the X on the button
    document.getElementById('magneto')?.classList.toggle('active');

    const x = document.getElementById('navbar') as HTMLDivElement;
    if (isNavbarOpen.value) {
      animateNavbarEnter('#navbar', '#navLinks li a', '.contact');
      x.focus();
    } else {
      animateNavbarLeave('#navbar', '#navLinks li a', '.contact');
      x.blur();
    }
  };

  const handleSectionClick = (e: Event, url: string) => {
    goToSection(e, url);
    toggleBtnClickAnimation();
  };

  const emit = defineEmits(['isLocked']);
  watch(isNavbarOpen, (newVal) => {
    emit('isLocked', newVal);
  });
</script>
